"use client"
import { useRouter, usePathname } from 'next/navigation'
import { AuthContextProvider } from './context/AuthContext'
import './globals.css'
import { Montserrat } from 'next/font/google'
import ProtectedRoute from './ProtectedRoute'

const noAuthRequired = ['/', '/register']
const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'E-Inspect',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  const router = useRouter()
  const routerPathname = usePathname()
  console.log(routerPathname)
  return (
      <html lang="en">
        <body className={inter.className}>
          { noAuthRequired.includes(routerPathname) ? (
        <AuthContextProvider>
          {children}
        </AuthContextProvider>

          ): (
              <AuthContextProvider>
                <ProtectedRoute>  
                  {children}
                </ProtectedRoute>
              </AuthContextProvider>
          )}
          
        </body>
      </html>
    
  )
}
